"""Engineering LLM Review domain models.

The Engineering LLM Review layer produces a structured, human-readable
engineering assessment of the repository — generated by an LLM that
receives **only** the processed outputs of the Evidence, Root Cause,
and Planning engines (never raw analyzer data).

Design principles:
    - **Evidence-bound**: Every claim in the review must reference the
      evidence or planning step that motivates it. The LLM is explicitly
      instructed not to invent new technical facts.
    - **Confidence-tagged**: Each review section carries a confidence
      level so the reader knows which conclusions are well-supported and
      which are speculative.
    - **Challenge-aware**: The review includes a "Challenge" section where
      the LLM critiques the planning engine's output — not just validates it.
    - **Offline-capable**: If the LLM is unavailable, a deterministic
      fallback review is produced from the planning engine output.

Integration:
    - :class:`EngineeringLLMReview` is attached to :class:`AnalysisResult`
      via the optional ``engineering_review`` field (backward compatible).
    - :class:`EngineeringReviewer` reads an :class:`EngineeringPlan` +
      :class:`RootCauseCollection` + :class:`EvidenceCollection` and
      produces an :class:`EngineeringLLMReview`.
    - No existing engine, builder, or analyzer is modified.
"""

from __future__ import annotations

from enum import Enum
from typing import Any
from uuid import UUID, uuid4

from pydantic import BaseModel, ConfigDict, Field


class ReviewConfidence(str, Enum):
    """Confidence level for a review section or recommendation."""

    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    SPECULATIVE = "speculative"


class ReviewSectionType(str, Enum):
    """The kind of section in an engineering review."""

    EXECUTIVE_SUMMARY = "executive_summary"
    ARCHITECTURE_REVIEW = "architecture_review"
    TOP_ROOT_CAUSES = "top_root_causes"
    HIGHEST_ROI_REFACTORING = "highest_roi_refactoring"
    RISK_ASSESSMENT = "risk_assessment"
    ENGINEERING_RECOMMENDATIONS = "engineering_recommendations"
    TRADE_OFF_ANALYSIS = "trade_off_analysis"
    MIGRATION_ADVICE = "migration_advice"
    LONG_TERM_VISION = "long_term_vision"
    CHALLENGE = "challenge"


class ReviewSection(BaseModel):
    """A single section of the engineering review.

    Each section has a type, a title, the body text, a confidence level,
    and optional references to evidence/planning items that support it.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    section_type: ReviewSectionType
    title: str
    body: str = Field(description="The review text for this section.")
    confidence: ReviewConfidence = ReviewConfidence.MEDIUM
    supporting_evidence_ids: list[UUID] = Field(default_factory=list)
    supporting_step_ids: list[UUID] = Field(default_factory=list)
    metadata: dict[str, Any] = Field(default_factory=dict)


class ChallengeItem(BaseModel):
    """A single critique of the planning engine's output.

    The LLM is asked to challenge — not just validate — the engineering
    plan. Each challenge identifies a potential weakness, unsupported
    assumption, or alternative approach.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    id: UUID = Field(default_factory=uuid4)
    target_step_id: UUID | None = None
    challenge_type: str = Field(
        description="'too_aggressive', 'too_conservative', 'insufficient_evidence', "
        "'alternative_approach', 'missing_context', 'risk_underestimated'."
    )
    description: str = Field(description="What the LLM challenges and why.")
    alternative: str | None = Field(
        default=None, description="A suggested alternative approach, if any."
    )
    confidence: ReviewConfidence = ReviewConfidence.MEDIUM


class EngineeringRecommendation(BaseModel):
    """A single LLM-generated engineering recommendation.

    Unlike the planning engine's deterministic steps, these recommendations
    carry the LLM's qualitative assessment — including confidence and
    rationale.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    id: UUID = Field(default_factory=uuid4)
    title: str
    description: str
    priority: str = Field(default="medium", description="critical/high/medium/low.")
    confidence: ReviewConfidence = ReviewConfidence.MEDIUM
    rationale: str = Field(description="Why this recommendation is made.")
    linked_step_ids: list[UUID] = Field(default_factory=list)
    linked_root_cause_ids: list[UUID] = Field(default_factory=list)


class EngineeringLLMReview(BaseModel):
    """The complete LLM-generated engineering review.

    This is the **final output** of the LLM layer — a structured,
    confidence-tagged, evidence-bound assessment that a Staff Engineer
    would produce after reading the analysis results.

    Structure:
        - ``sections``: ordered review sections (executive summary, arch
          review, risk assessment, etc.).
        - ``challenges``: critiques of the planning engine.
        - ``recommendations``: LLM-generated recommendations with rationale.
        - ``model_info``: which LLM provider/model produced this review.
        - ``offline``: ``True`` if this review was produced without an LLM
          (deterministic fallback).
    """

    model_config = ConfigDict(frozen=True, extra="forbid", arbitrary_types_allowed=True)

    id: UUID = Field(default_factory=uuid4)
    sections: list[ReviewSection] = Field(default_factory=list)
    challenges: list[ChallengeItem] = Field(default_factory=list)
    recommendations: list[EngineeringRecommendation] = Field(default_factory=list)

    # LLM metadata.
    model_info: dict[str, Any] = Field(default_factory=dict)
    offline: bool = Field(default=False, description="True if produced without an LLM (fallback).")
    generated_at: str | None = None

    # Token usage (for cost tracking).
    prompt_tokens: int = Field(default=0, ge=0)
    completion_tokens: int = Field(default=0, ge=0)

    # Summary statistics.
    statistics: dict[str, Any] = Field(default_factory=dict)

    @property
    def total_sections(self) -> int:
        """Number of review sections."""
        return len(self.sections)

    @property
    def total_challenges(self) -> int:
        """Number of planning-engine challenges."""
        return len(self.challenges)

    def get_section(self, section_type: ReviewSectionType) -> ReviewSection | None:
        """Return the section of a given type, if present."""
        for section in self.sections:
            if section.section_type == section_type:
                return section
        return None


__all__ = [
    "ChallengeItem",
    "EngineeringLLMReview",
    "EngineeringRecommendation",
    "ReviewConfidence",
    "ReviewSection",
    "ReviewSectionType",
]
